# makfile configuration
CPU             	= msp430g2553
CFLAGS          	= -mmcu=${CPU} -Os -I../h
LDFLAGS		= -L../lib -L/opt/ti/msp430_gcc/include/ 

#switch the compiler (for the internal make rules)
CC              = msp430-elf-gcc
AS              = msp430-elf-gcc -mmcu=${CPU} -c

all:tiltscreen.elf

#additional rules for files
tiltscreen.elf: ${COMMON_OBJECTS} tiltscreen.o ../lib/libp2sw.a wdt_handler.o
	${CC} ${CFLAGS} ${LDFLAGS} -o $@ $^  -lTimer -lLcd -lShape -lCircle 

load: tiltscreen.elf
	mspdebug rf2500 "prog $^"

clean:
	rm -f *.o *.elf
